server:
  host: 0.0.0.0
  port: 4224
  options:
    connections:
      routes:
        cors:
          origin: ['http://0.0.0.0:4242', 'http://localhost:4242', 'http://127.0.0.1:4242']
swag:
  info:
    title: Redirectr API with Hapiness
mongodb:
  host: 127.0.0.1
  port: 27017
  db: redirectr
options:
  connections:
    routes:
      cors:
        origin: ['http://0.0.0.0:4242', 'http://localhost:4242', 'http://127.0.0.1:4242']
