server:
  host: 0.0.0.0
  port: 4224
  options:
    connections:
      routes:
        cors:
          origin: ['http://0.0.0.0:4444']
swag:
  info:
    title: Redirectr API with Hapiness
mongodb:
  host: 127.0.0.1
  port: 27017
  db: redirectr
